### ISSUE TITLE
Tables in pre-generated PDFs not reflowed

### ISSUE THREAD

**Issue by chipzoller** [dohsimpson/kubernetes-doc-pdf#1]
First, LOVE you've done this so thank you! I'm finding that many tables in the PDF docs you've stored in the repo have rightmost columns truncated when viewing in Android Acrobat Reader. I've not tried running the script on-demand. Is this something that's fixable?

**Comment by dohsimpson** [comment]
Hi Chip,

Would you mind sharing a screenshot?

**Comment by chipzoller** [comment]
Hi, try p17 in Concepts.pdf. In two devices, the table looks like the following:

https://www.dropbox.com/s/9615ufa6jlmm3tk/Screenshot_20190706-073311.png?dl=0

**Comment by dohsimpson** [comment]
This seems to an issue with `xelatex` not able to preserve some of the formattings of HTML tables, in particular, the word-break and overflow-wrap property. Switching the PDF engine to `weasyprint` solves the issue of html tables, but introduces new issues with image width and missing TOC, which are both fixable I think. 

Give this file a try, and thanks for using my project :)

[Concepts.pdf](https://github.com/dohsimpson/kubernetes-doc-pdf/files/3364838/z.pdf)

**Comment by chipzoller** [comment]
Yes, that does seem to preserve the tables, but absent are the extremely valuable PDF bookmarks that show sections/chapters which, given the large size of a couple of these docs, is fairly important.

**Comment by dohsimpson** [comment]
Hi,

Sorry for the late reply. I've been busy this week. Here's the PDF with bookmarks, hope it helps you for now. Once I figured out how to set the image width, I'll update the repo.

[Concepts.pdf](https://github.com/dohsimpson/kubernetes-doc-pdf/files/3389870/Concepts.pdf)

**Comment by chipzoller** [comment]
Thanks very much for that, @dohsimpson it's appreciated. A couple other things to report with the latest version with regard to the rendering engine.

1. Code comments don't get wrapped (PDF p92; see corresponding online page [here](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/))
2. Embedded images are scaled to tiny size (PDF p95; see corresponding online page [here](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/pods/pod-overview/))
3. Open and close double quotes are getting rendered as "â€oe" and "â€FD" respectively (PDF p94; see corresponding online page [here](https://v1-14.docs.kubernetes.io/docs/concepts/workloads/pods/pod-overview/))
4. Horizontal scrolling console output is truncated (PDF p78-79; see corresponding online page [here](https://v1-14.docs.kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/))

**Comment by dohsimpson** [comment]
Awesome! Thanks for the report! I'll see if I can fix them.

**Comment by chipzoller** [comment]
Let me know how else I can help. While the K8s online documentation is great, what's severely missing out  there is a PDF format of it so it can be viewed for easy offline reading on a tablet. Your project solves that, so thank **you**!

**Comment by dohsimpson** [comment]
Hi Chip,

Most of the issues are fixed except some unicode characters are not rendered correctly, e.g. âœ”. However, I did patched single quote and double quote, so those should display normally.

**Comment by chipzoller** [comment]
This is excellent, @dohsimpson. Thank you for this hard work. I'm going through them now and also opened a couple other issues that I think would help to improve these further. I know I as well as others will spend hours pouring over these PDFs!

**Comment by dohsimpson** [comment]
Hi Chip,

Thanks for the feedback. I will close this issue now.
