### ISSUE TITLE
Publish PDF as Release on github

### ISSUE THREAD

**Issue by guibirow** [dohsimpson/kubernetes-doc-pdf#10]
Hi, thanks for taking the time to convert the docs into PDF, it is really useful,

Would be amazing if you publish these into github releases so we could download docs for a specific release and also know which release is the current.

**Comment by dohsimpson** [comment]
Hi @guibirow , thanks for the suggestion. I agree with you that it would be better to have access to the past version of the documentation as releases.

Unfortunately, given the time constraint I have, the only commitment I can give is to maintain the up to date version of the documents.

I do hope that you can achieve what you wished for by using the commit history to navigate upload history, as an ad-hoc method for this purpose.
