### ISSUE TITLE
Support to change languaje

### ISSUE THREAD

**Issue by Conkernel** [dohsimpson/kubernetes-doc-pdf#14]
Hi, thanks a lot for all this effort. It is very useful.

I've read how somebody asked to use the chinesse version of the documentation. I've followed some changes made on the kubernetes-doc.py file to pint to the spanish version: "https://kubernetes.io/es/docs/". The problem is that after performing the "./gen_ref_docs.sh", some parts of the files are like empty. An exaqmple could be the file Setup.pdf attached here
[Setup.pdf](https://github.com/dohsimpson/kubernetes-doc-pdf/files/15278003/Setup.pdf)

I'd like some help in order to fix it and get a usefull pdf file.

Thanks in advance!

**Comment by dohsimpson** [comment]
Hi @Conkernel , glad you find my project useful!

The `gen_ref_docs.sh` file only generates the `kubectl-commands.pdf` file, and does not change other PDF files.

My guess is that there was some issues when you run `python kubernetes-doc.py`.

Could you share the output of the above command when you generate the *setup.pdf* file?

**Comment by Conkernel** [comment]
Hi!!
Thanks for your answer.

Actualy, Irealized that the problem was that some parts of the documentation were not already (or not anymore) translated to spanish, but the rest of the Doc was succesfully converted to .pdf

Thanks again for all this great work!!
