### ISSUE TITLE
Redact "Feedback" sub-sections

### ISSUE THREAD

**Issue by chipzoller** [dohsimpson/kubernetes-doc-pdf#2]
At the end of each section of the Kubernetes documentation appears a "[Feedback](https://kubernetes.io/docs/reference/#feedback)" sub-section designed, ostensibly, to provide feedback on the quality of the current page. This makes perfect sense when viewed live, in a web browser. It, however, only serves to bloat (if slightly) an offline archive of the same documentation occupying, when present, ~20–25% of a given PDF page's layout.

![image](https://user-images.githubusercontent.com/29008123/61584832-cdb2ec80-ab1c-11e9-97c0-fbfb9970f17a.png)

It would make these already nice offline docs look even better, more streamlined, and less full than they currently are. I would suggest, if this change is implemented, to make it the default for your auto-generated PDFs and, if so desired, activated manually with a switch should other users wish to retain it.

**Comment by dohsimpson** [comment]
This seems to be fixed for the current version of kubernetes docs. Feedback used to be part of .td-content div, which is the main content div, and therefore makes it hard to exclude. But now kube doc moved it outside the .td-content div, so now my generator code automatically exclude it.
