### ISSUE TITLE
Recommended Labels in Concepts.pdf seems to be in the wrong place

### ISSUE THREAD

**Issue by tlazaro** [dohsimpson/kubernetes-doc-pdf#9]
In page 4 of Concepts.pdf I can see Recommended Labels which should be in much later pages.

**Comment by dohsimpson** [comment]
Hi @tlazaro, this is indeed a bug. Thanks for reporting it! I made a fix and updated the PDF files. If you find anything else in the wrong place or missing, feel free to reach out again.

**Comment by tlazaro** [comment]
Awesome thanks!
